service: ermin-maksumic-lambda-hex
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    TABLE_NAME:
      Ref: productMaksumic
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource:
      - "Fn::GetAtt": [productMaksumic, Arn]
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /stocks/{id}
          method: get
      - httpApi:
          path: /products/getById/{id}
          method: get
      - httpApi:
          path: /products
          method: get
      - httpApi:
          path: /products/edit/{id}
          method: put
      - httpApi:
          path: /products/post
          method: post
      - httpApi:
          path: /products/delete/{id}
          method: delete
resources:
  Resources:
    productMaksumic:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: productMaksumic
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1